export const SERVICES_URL = 'https://services-ds-core-91.dalilsubhi.com';
export const COMMUNITY_HUB_URL = 'https://services-ds-core-91.dalilsubhi.com/community';
export const RENTALS_URL = 'https://rentals-ds-core-91.dalilsubhi.com/rentals';
export const REAL_ESTATE_URL = 'https://realestate-ds-core-91.dalilsubhi.com';
export const RESIDENT_APP_URL = 'https://app-ds-core-91.dalilsubhi.com';
export const OWNERS_URL = 'https://rentals-ds-core-91.dalilsubhi.com/owners/list-your-unit';
export const WHATSAPP_GROUP_URL = 'https://chat.whatsapp.com/ECEZfbsvjlU43eDvKa9XUu';
export const FACEBOOK_GROUP_URL = 'https://www.facebook.com/share/g/1CzbCwjugk/?mibextid=KtfwRi';
export const MAIN_URL = 'https://dalilsubhi.com/';
